# Shared constants for NRS Bridge Connection

DEFAULT_EXCLUDED_DOCTYPES = [
	"NRS Bridge Settings",
	"Error Log",
	"Activity Log",
	"Route History",
	"Version",
	"Sessions",
	"Scheduled Job Log",
	"Prepared Report",
	"DocType",
	"Custom Field",
	"Property Setter",
	"Print Format",
	"Report",
	"Workspace",
	"Role",
	"User",
	"Installed Application",
	"Module Def",
	"Patch Log",
	"Singles",
	"Comment",
	"Stock Ledger Entry",
	"GL Entry",
	"Payment Ledger Entry",
	"Repost Item Valuation",
	"Communication",
	"Email Queue",
	"Audit Trail",
	"Access Log",
	"DocShare",
	"View Log",
	"Submission Queue",
	"Bin",
	"Item Valuation Rate",
	"Serial and Batch Bundle",
	"Stock Reposting Error Log",
	"Integration Request",
	"Webhook Request Log",
]
